spring:
  application:
    name: msgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_SERVER}:${KEYCLOAK_PORT}/realms/mscourserealm

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:l&e6KZ61wQr3@${EUREKA_SERVER}:8761/eureka
